INSERT INTO
    articles(picture, description, title, price)
VALUES
("https://firebasestorage.googleapis.com/v0/b/refashioned-e26ba.appspot.com/o/photosfashion%2Fbella.png?alt=media&token=3ca50807-853c-4b99-8ac7-00aaa52b75f3", "Révélez votre côté bohème avec notre robe en crochet. Légère, aérée et artistique, cette pièce unique vous enveloppera d'un charme authentique. Parfaitement adaptée aux journées ensoleillées et aux escapades estivales, cette robe en crochet vous fera rayonner avec style. Faites-en votre incontournable mode dès aujourd'hui !", "Robe Bella", 35),
("https://firebasestorage.googleapis.com/v0/b/refashioned-e26ba.appspot.com/o/photosfashion%2Felea.png?alt=media&token=7adfa37d-7034-4cc1-ab66-8b95d963df08", "Charme et élégance combinés dans notre chemise robe blanche. Un look polyvalent et raffiné, parfait pour toute occasion. Optez pour un style frais et intemporel dès maintenant !","Robe Elea", 37),
("https://firebasestorage.googleapis.com/v0/b/refashioned-e26ba.appspot.com/o/photosfashion%2Fgabrielle.png?alt=media&token=9acc729d-0d24-498e-b8c3-3a6d4ec6f408", "Adoptez le charme décontracté de notre chemise en lin kaki. Une pièce essentielle pour un look à la fois élégant et décontracté. Son tissu en lin léger vous offre une sensation de fraîcheur tout en ajoutant une touche de sophistication.", "Chemise Gabrielle", 25),
("https://firebasestorage.googleapis.com/v0/b/refashioned-e26ba.appspot.com/o/photosfashion%2Fjulie.png?alt=media&token=a3d4bd04-db8b-423e-bcf3-596aaa8c78ea", "Adoptez le confort et l'élégance estivale avec notre short en lin blanc. Un essentiel de votre garde-robe pour les journées chaudes. Sa texture légère en lin vous procure une sensation de fraîcheur, idéale pour les moments de détente ou les aventures en plein air.", "Short Julie", 35),
("https://firebasestorage.googleapis.com/v0/b/refashioned-e26ba.appspot.com/o/photosfashion%2Flaetitia.png?alt=media&token=308f9de3-ee0f-48d0-ac55-71d9c85be87b", "Optez pour la simplicité raffinée de notre chemise en lin blanc. Un véritable incontournable pour une élégance décontractée. Son tissu léger en lin vous offre une sensation de fraîcheur, parfaite pour les journées ensoleillées.", "Chemise Laetitia", 28),
("https://firebasestorage.googleapis.com/v0/b/refashioned-e26ba.appspot.com/o/photosfashion%2Flinda.png?alt=media&token=93258fa0-b4dc-4f64-97e6-132d864d7dfa", "Optez pour l'audace et l'élégance de notre petite robe noire moulante d'été. Une pièce essentielle pour vos soirées estivales. Sa coupe ajustée met en valeur vos courbes avec confiance et assurance, vous offrant un look séduisant et chic.", "Robe Linda", 19),
("https://firebasestorage.googleapis.com/v0/b/refashioned-e26ba.appspot.com/o/photosfashion%2Flola.png?alt=media&token=9904e80c-1636-4f1f-b2cb-27ca7d4c7757", "Osez l'élégance et le glamour avec notre robe noire moulante longue d'été. Une pièce raffinée qui allie confort et séduction. Sa coupe longue épouse parfaitement vos courbes, mettant en valeur votre silhouette avec une touche de sophistication.", "Robe Lola", 35),
("https://firebasestorage.googleapis.com/v0/b/refashioned-e26ba.appspot.com/o/photosfashion%2Flucia.png?alt=media&token=e23f8cf0-6c4e-4d0f-884a-32578816e447", "Sublimez votre élégance avec notre robe de soirée en satin beige. Douceur et sophistication s'allient pour vous offrir un look intemporel. Soyez resplendissante lors de vos soirées spéciales.", "Robe Lucie", 40),
("https://firebasestorage.googleapis.com/v0/b/refashioned-e26ba.appspot.com/o/photosfashion%2Flucile.png?alt=media&token=ed7f44ed-b46e-4d1e-aeb8-892c8d775a43", "Adoptez le confort décontracté avec notre chemise bleue oversize. Une pièce tendance qui allie style et aisance. Sa coupe ample vous procure une sensation de liberté et de légèreté, parfaite pour les journées détente ou les sorties entre amis.", "Chemise Lucile", 25),
("https://firebasestorage.googleapis.com/v0/b/refashioned-e26ba.appspot.com/o/photosfashion%2Fmanon.png?alt=media&token=0942776b-ccbf-48f5-9b22-d9e28b984baa", "Faites ressortir votre féminité avec notre ensemble chemise et short en lin rose. Une tenue estivale à la fois chic et confortable. La chemise légère en lin rose ajoute une touche de douceur à votre look, tandis que le short assorti vous offre une allure moderne et décontractée", "Ensemble Manon", 45),
("https://firebasestorage.googleapis.com/v0/b/refashioned-e26ba.appspot.com/o/photosfashion%2Fmarine.png?alt=media&token=1396b41c-40dc-4c78-88f9-0a6bc5335b62", "Faites sensation avec notre top en crochet beige. Une pièce bohème et raffinée qui ajoutera une touche de charme à votre garde-robe estivale. Le délicat travail au crochet crée un look aéré et élégant, parfait pour les journées ensoleillées.", "Top Marine", 15),
("https://firebasestorage.googleapis.com/v0/b/refashioned-e26ba.appspot.com/o/photosfashion%2Fsofia.png?alt=media&token=3d7fdda8-c948-4c71-b67a-fee56aedab46", "Optez pour l'audace et l'élégance de notre robe noire courte décolletée. Une pièce séduisante qui captivera tous les regards. Sa coupe courte flatteuse mettra en valeur vos jambes avec confiance et assurance, tandis que le décolleté plongeant ajoutera une touche sensuelle et raffinée à votre look.", "Robe Sofia", 35);




CREATE TABLE articles (
    `id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `picture` TEXT,
    `description` TEXT,
    `title` TEXT,
    `price` INT,
);